pref("extensions.less.useFilewatcher", false);
pref("extensions.less.compilerEnabled", true);
pref("extensions.less.compressFile", false);
pref("extensions.less.fileWatcher", "");
pref("extensions.less.tooltipY", 8);
pref("extensions.less.showWarning", true);
pref("extensions.less.msgType", "web-notifications");
pref("extensions.less.useFileScopes", false);
pref("extensions.less.fileScopes", "[]");
